apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver-fruits
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: uhs13/publickubernetesenv:v2
        envFrom:
          - configMapRef:
              name: goserver-configmap
        volumeMounts:
        - mountPath: "/go/fruits"
          name: fruits

      volumes:
      - name: fruits
        configMap:
          name: configmapfruits
          items:
          - key: fruits
            path: "fruits.txt"
