apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: uhs13/publickubernetesenv:latest
        env:
          - name: "NAME"
            value: "John Cena"
          - name: "COLOR"
            value: "Orange"
